assert(require("tests.quality_spec").run())
print("quality_spec: PASS")
assert(require("tests.clustered_spec").run())
print("clustered_spec: PASS")
assert(require("tests.hdr_spec").run())
print("hdr_spec: PASS")
